; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=riscv32 -mattr=+zcheripurecap,+cap-mode -target-abi=il32pc64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s
; RUN: llc -mtriple=riscv64 -mattr=+zcheripurecap,+cap-mode -target-abi=l64pc128 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=riscv32 -mattr=+zicbop,+zcheripurecap,+cap-mode -target-abi=il32pc64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32ZICBOP %s
; RUN: llc -mtriple=riscv64 -mattr=+zicbop,+zcheripurecap,+cap-mode -target-abi=l64pc128 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64ZICBOP %s
; RUN: llc -mtriple=riscv64 -mattr=+zicbop,+zihintntl,+zcheripurecap,+cap-mode -target-abi=l64pc128 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64ZICBOPZIHINTNTL %s

declare void @llvm.prefetch.p200(ptr addrspace(200), i32, i32, i32)

define void @test_prefetch_read_locality_0(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_read_locality_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_read_locality_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_read_locality_0:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_read_locality_0:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_read_locality_0:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_write_locality_0(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_write_locality_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_write_locality_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_write_locality_0:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_write_locality_0:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_write_locality_0:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 1, i32 0, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_0(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_instruction_locality_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_instruction_locality_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_instruction_locality_0:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_instruction_locality_0:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_instruction_locality_0:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 0, i32 0)
  ret void
}

define void @test_prefetch_read_locality_1(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_read_locality_1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_read_locality_1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_read_locality_1:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_read_locality_1:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_read_locality_1:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.pall
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 1, i32 1)
  ret void
}

define void @test_prefetch_write_locality_1(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_write_locality_1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_write_locality_1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_write_locality_1:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_write_locality_1:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_write_locality_1:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.pall
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 1, i32 1, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_1(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_instruction_locality_1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_instruction_locality_1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_instruction_locality_1:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_instruction_locality_1:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_instruction_locality_1:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.pall
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 1, i32 0)
  ret void
}

define void @test_prefetch_read_locality_2(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_read_locality_2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_read_locality_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_read_locality_2:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_read_locality_2:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_read_locality_2:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.p1
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 2, i32 1)
  ret void
}

define void @test_prefetch_write_locality_2(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_write_locality_2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_write_locality_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_write_locality_2:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_write_locality_2:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_write_locality_2:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.p1
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 1, i32 2, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_2(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_instruction_locality_2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_instruction_locality_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_instruction_locality_2:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_instruction_locality_2:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_instruction_locality_2:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.p1
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 2, i32 0)
  ret void
}

define void @test_prefetch_read_locality_3(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_read_locality_3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_read_locality_3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_read_locality_3:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_read_locality_3:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_read_locality_3:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 3, i32 1)
  ret void
}

define void @test_prefetch_write_locality_3(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_write_locality_3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_write_locality_3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_write_locality_3:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_write_locality_3:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_write_locality_3:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.w 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 1, i32 3, i32 1)
  ret void
}

define void @test_prefetch_instruction_locality_3(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_instruction_locality_3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_instruction_locality_3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_instruction_locality_3:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_instruction_locality_3:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_instruction_locality_3:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.i 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  call void @llvm.prefetch.p200(ptr addrspace(200) %a, i32 0, i32 3, i32 0)
  ret void
}

define void @test_prefetch_offsetable_0(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_0:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_0:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_0:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 2016
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_1(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_1:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_1:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_1:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 -2048
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_2(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_2:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r 32(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_2:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r 32(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_2:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 32(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 32
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_3(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_3:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    prefetch.r -32(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_3:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    prefetch.r -32(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_3:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -32(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 -32
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_4(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_4:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_4:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_4:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi ca0, ca0, 32
; RV32ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_4:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi ca0, ca0, 32
; RV64ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_4:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, 32
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 2048
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_5(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_5:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_5:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_5:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi ca0, ca0, -1
; RV32ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_5:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi ca0, ca0, -1
; RV64ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_5:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, -1
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 -2049
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_6(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_6:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_6:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_6:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi ca0, ca0, 16
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_6:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi ca0, ca0, 16
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_6:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, 16
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 16
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_7(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_7:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_7:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_7:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi ca0, ca0, -16
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_7:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi ca0, ca0, -16
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_7:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, -16
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 -16
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_9(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_9:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_9:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_9:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    lui a1, 1
; RV32ZICBOP-NEXT:    addi a1, a1, 64
; RV32ZICBOP-NEXT:    cadd ca0, ca0, a1
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_9:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    lui a1, 1
; RV64ZICBOP-NEXT:    addiw a1, a1, 64
; RV64ZICBOP-NEXT:    cadd ca0, ca0, a1
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_9:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    lui a1, 1
; RV64ZICBOPZIHINTNTL-NEXT:    addiw a1, a1, 64
; RV64ZICBOPZIHINTNTL-NEXT:    cadd ca0, ca0, a1
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 4160
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_offsetable_8(ptr addrspace(200) %a) nounwind {
; RV32I-LABEL: test_prefetch_offsetable_8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_offsetable_8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_offsetable_8:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    lui a1, 1048575
; RV32ZICBOP-NEXT:    addi a1, a1, -64
; RV32ZICBOP-NEXT:    cadd ca0, ca0, a1
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_offsetable_8:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    lui a1, 1048575
; RV64ZICBOP-NEXT:    addiw a1, a1, -64
; RV64ZICBOP-NEXT:    cadd ca0, ca0, a1
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_offsetable_8:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    lui a1, 1048575
; RV64ZICBOPZIHINTNTL-NEXT:    addiw a1, a1, -64
; RV64ZICBOPZIHINTNTL-NEXT:    cadd ca0, ca0, a1
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %addr = getelementptr i8, ptr addrspace(200) %a, i64 -4160
  call void @llvm.prefetch.p200(ptr addrspace(200) %addr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_0() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_0:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_0:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_0:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 0
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_1() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -2032
; RV32I-NEXT:    sc cra, 2024(csp) # 8-byte Folded Spill
; RV32I-NEXT:    sc cs0, 2016(csp) # 8-byte Folded Spill
; RV32I-NEXT:    caddi cs0, csp, 2032
; RV32I-NEXT:    caddi csp, csp, -2048
; RV32I-NEXT:    caddi csp, csp, -144
; RV32I-NEXT:    andi a0, sp, -64
; RV32I-NEXT:    scaddr csp, csp, a0
; RV32I-NEXT:    lui a0, 1048575
; RV32I-NEXT:    addi a0, a0, -128
; RV32I-NEXT:    cadd csp, cs0, a0
; RV32I-NEXT:    caddi csp, csp, 2032
; RV32I-NEXT:    caddi csp, csp, 160
; RV32I-NEXT:    lc cra, 2024(csp) # 8-byte Folded Reload
; RV32I-NEXT:    lc cs0, 2016(csp) # 8-byte Folded Reload
; RV32I-NEXT:    caddi csp, csp, 2032
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a0, 1048575
; RV64I-NEXT:    addiw a0, a0, -16
; RV64I-NEXT:    cadd csp, csp, a0
; RV64I-NEXT:    lui a0, 1
; RV64I-NEXT:    addiw a0, a0, 16
; RV64I-NEXT:    cadd csp, csp, a0
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_1:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -2032
; RV32ZICBOP-NEXT:    sc cra, 2024(csp) # 8-byte Folded Spill
; RV32ZICBOP-NEXT:    sc cs0, 2016(csp) # 8-byte Folded Spill
; RV32ZICBOP-NEXT:    caddi cs0, csp, 2032
; RV32ZICBOP-NEXT:    caddi csp, csp, -2048
; RV32ZICBOP-NEXT:    caddi csp, csp, -144
; RV32ZICBOP-NEXT:    andi a0, sp, -64
; RV32ZICBOP-NEXT:    scaddr csp, csp, a0
; RV32ZICBOP-NEXT:    lui a0, 1
; RV32ZICBOP-NEXT:    caddi ca1, csp, 64
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    lui a0, 1048575
; RV32ZICBOP-NEXT:    addi a0, a0, -128
; RV32ZICBOP-NEXT:    cadd csp, cs0, a0
; RV32ZICBOP-NEXT:    caddi csp, csp, 2032
; RV32ZICBOP-NEXT:    caddi csp, csp, 160
; RV32ZICBOP-NEXT:    lc cra, 2024(csp) # 8-byte Folded Reload
; RV32ZICBOP-NEXT:    lc cs0, 2016(csp) # 8-byte Folded Reload
; RV32ZICBOP-NEXT:    caddi csp, csp, 2032
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_1:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    lui a0, 1048575
; RV64ZICBOP-NEXT:    addiw a0, a0, -16
; RV64ZICBOP-NEXT:    cadd csp, csp, a0
; RV64ZICBOP-NEXT:    lui a0, 1
; RV64ZICBOP-NEXT:    caddi ca1, csp, 16
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    lui a0, 1
; RV64ZICBOP-NEXT:    addiw a0, a0, 16
; RV64ZICBOP-NEXT:    cadd csp, csp, a0
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_1:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    lui a0, 1048575
; RV64ZICBOPZIHINTNTL-NEXT:    addiw a0, a0, -16
; RV64ZICBOPZIHINTNTL-NEXT:    cadd csp, csp, a0
; RV64ZICBOPZIHINTNTL-NEXT:    lui a0, 1
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 16
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    lui a0, 1
; RV64ZICBOPZIHINTNTL-NEXT:    addiw a0, a0, 16
; RV64ZICBOPZIHINTNTL-NEXT:    cadd csp, csp, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [1024 x i32], align 4, addrspace(200)
  call void @llvm.prefetch.p200(ptr addrspace(200) %data, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_2() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_2:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    caddi ca0, ca0, 16
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_2:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    caddi ca0, ca0, 16
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_2:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, 16
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 4
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_3() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_3:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    caddi ca0, ca0, -16
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_3:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    caddi ca0, ca0, -16
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_3:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, -16
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 -4
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_4() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_4:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_4:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_4:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    prefetch.r 32(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_4:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    prefetch.r 32(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_4:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 32(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 8
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_5() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_5:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_5:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_5:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    prefetch.r -32(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_5:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    prefetch.r -32(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_5:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -32(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 -8
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_6() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_6:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_6:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_6:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_6:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_6:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 504
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_7() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_7:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_7:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_7:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_7:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_7:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 -512
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_8() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_8:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    caddi ca0, ca0, 2020
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_8:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    caddi ca0, ca0, 2020
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_8:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, 2020
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 505
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_frameindex_9() nounwind {
; RV32I-LABEL: test_prefetch_frameindex_9:
; RV32I:       # %bb.0:
; RV32I-NEXT:    caddi csp, csp, -512
; RV32I-NEXT:    caddi csp, csp, 512
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_frameindex_9:
; RV64I:       # %bb.0:
; RV64I-NEXT:    caddi csp, csp, -512
; RV64I-NEXT:    caddi csp, csp, 512
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_frameindex_9:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:    caddi csp, csp, -512
; RV32ZICBOP-NEXT:    li a0, 512
; RV32ZICBOP-NEXT:    caddi ca1, csp, 0
; RV32ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV32ZICBOP-NEXT:    caddi ca0, ca0, -4
; RV32ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV32ZICBOP-NEXT:    caddi csp, csp, 512
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_frameindex_9:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:    caddi csp, csp, -512
; RV64ZICBOP-NEXT:    li a0, 512
; RV64ZICBOP-NEXT:    caddi ca1, csp, 0
; RV64ZICBOP-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOP-NEXT:    caddi ca0, ca0, -4
; RV64ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOP-NEXT:    caddi csp, csp, 512
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_frameindex_9:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, -512
; RV64ZICBOPZIHINTNTL-NEXT:    li a0, 512
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca1, csp, 0
; RV64ZICBOPZIHINTNTL-NEXT:    scbndsr ca0, ca1, a0
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, -4
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi csp, csp, 512
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %data = alloca [128 x i32], align 4, addrspace(200)
  %ptr = getelementptr [128 x i32], ptr addrspace(200) %data, i32 0, i32 -513
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

@g = external addrspace(200) global [1024 x i32], align 4

define void @test_prefetch_global_0() nounwind {
; RV32I-LABEL: test_prefetch_global_0:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_0:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB32_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB32_1)(ca0)
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_0:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB32_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB32_1)(ca0)
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_0:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB32_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB32_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 0
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_1() nounwind {
; RV32I-LABEL: test_prefetch_global_1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_1:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB33_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB33_1)(ca0)
; RV32ZICBOP-NEXT:    caddi ca0, ca0, 16
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_1:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB33_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB33_1)(ca0)
; RV64ZICBOP-NEXT:    caddi ca0, ca0, 16
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_1:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB33_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB33_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, 16
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 4
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_2() nounwind {
; RV32I-LABEL: test_prefetch_global_2:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_2:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB34_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB34_1)(ca0)
; RV32ZICBOP-NEXT:    caddi ca0, ca0, -16
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_2:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB34_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB34_1)(ca0)
; RV64ZICBOP-NEXT:    caddi ca0, ca0, -16
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_2:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB34_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB34_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, -16
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 -4
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_3() nounwind {
; RV32I-LABEL: test_prefetch_global_3:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_3:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB35_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB35_1)(ca0)
; RV32ZICBOP-NEXT:    prefetch.r 32(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_3:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB35_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB35_1)(ca0)
; RV64ZICBOP-NEXT:    prefetch.r 32(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_3:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB35_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB35_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 32(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 8
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_4() nounwind {
; RV32I-LABEL: test_prefetch_global_4:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_4:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_4:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB36_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB36_1)(ca0)
; RV32ZICBOP-NEXT:    prefetch.r -32(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_4:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB36_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB36_1)(ca0)
; RV64ZICBOP-NEXT:    prefetch.r -32(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_4:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB36_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB36_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -32(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 -8
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_5() nounwind {
; RV32I-LABEL: test_prefetch_global_5:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_5:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_5:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB37_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB37_1)(ca0)
; RV32ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_5:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB37_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB37_1)(ca0)
; RV64ZICBOP-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_5:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB37_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB37_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 2016(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 504
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_6() nounwind {
; RV32I-LABEL: test_prefetch_global_6:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_6:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_6:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB38_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB38_1)(ca0)
; RV32ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_6:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB38_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB38_1)(ca0)
; RV64ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_6:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB38_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB38_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 -512
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_7() nounwind {
; RV32I-LABEL: test_prefetch_global_7:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_7:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_7:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB39_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB39_1)(ca0)
; RV32ZICBOP-NEXT:    caddi ca0, ca0, 2020
; RV32ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_7:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB39_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB39_1)(ca0)
; RV64ZICBOP-NEXT:    caddi ca0, ca0, 2020
; RV64ZICBOP-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_7:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB39_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB39_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, 2020
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r 0(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 505
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}

define void @test_prefetch_global_8() nounwind {
; RV32I-LABEL: test_prefetch_global_8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_prefetch_global_8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV32ZICBOP-LABEL: test_prefetch_global_8:
; RV32ZICBOP:       # %bb.0:
; RV32ZICBOP-NEXT:  .LBB40_1: # Label of block must be emitted
; RV32ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV32ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB40_1)(ca0)
; RV32ZICBOP-NEXT:    caddi ca0, ca0, -4
; RV32ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV32ZICBOP-NEXT:    ret
;
; RV64ZICBOP-LABEL: test_prefetch_global_8:
; RV64ZICBOP:       # %bb.0:
; RV64ZICBOP-NEXT:  .LBB40_1: # Label of block must be emitted
; RV64ZICBOP-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOP-NEXT:    lc ca0, %pcrel_lo(.LBB40_1)(ca0)
; RV64ZICBOP-NEXT:    caddi ca0, ca0, -4
; RV64ZICBOP-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOP-NEXT:    ret
;
; RV64ZICBOPZIHINTNTL-LABEL: test_prefetch_global_8:
; RV64ZICBOPZIHINTNTL:       # %bb.0:
; RV64ZICBOPZIHINTNTL-NEXT:  .LBB40_1: # Label of block must be emitted
; RV64ZICBOPZIHINTNTL-NEXT:    auipc ca0, %got_pcrel_hi(g)
; RV64ZICBOPZIHINTNTL-NEXT:    lc ca0, %pcrel_lo(.LBB40_1)(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    caddi ca0, ca0, -4
; RV64ZICBOPZIHINTNTL-NEXT:    ntl.all
; RV64ZICBOPZIHINTNTL-NEXT:    prefetch.r -2048(ca0)
; RV64ZICBOPZIHINTNTL-NEXT:    ret
  %ptr = getelementptr [1024 x i32], ptr addrspace(200) @g, i32 0, i32 -513
  call void @llvm.prefetch.p200(ptr addrspace(200) %ptr, i32 0, i32 0, i32 1)
  ret void
}
