; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: %riscv32_cheri_purecap_opt < %s -loop-reduce -S | \
; RUN:   FileCheck %s --check-prefix=CHECK-PURECAP-RV32
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"

;; Ensure that LSR does not create traversal starting at a negative initial offset,
;; as those may not be representable on CHERI.

define dso_local i32 @strlen(ptr addrspace(200) noundef readonly %str) local_unnamed_addr addrspace(200) #0 {
; CHECK: entry:
; CHECK-NOT: -1
; CHECK-PURECAP-RV32-LABEL: define dso_local i32 @strlen(
; CHECK-PURECAP-RV32-SAME: ptr addrspace(200) noundef readonly [[STR:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-PURECAP-RV32-NEXT:  [[ENTRY:.*]]:
; CHECK-PURECAP-RV32-NEXT:    br label %[[FOR_COND:.*]]
; CHECK-PURECAP-RV32:       [[FOR_COND]]:
; CHECK-PURECAP-RV32-NEXT:    [[S_0:%.*]] = phi ptr addrspace(200) [ [[STR]], %[[ENTRY]] ], [ [[INCDEC_PTR:%.*]], %[[FOR_COND]] ]
; CHECK-PURECAP-RV32-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[S_0]], align 1
; CHECK-PURECAP-RV32-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-PURECAP-RV32-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds nuw i8, ptr addrspace(200) [[S_0]], i32 1
; CHECK-PURECAP-RV32-NEXT:    br i1 [[TOBOOL_NOT]], label %[[FOR_END:.*]], label %[[FOR_COND]]
; CHECK-PURECAP-RV32:       [[FOR_END]]:
; CHECK-PURECAP-RV32-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.cheri.cap.diff.i32(ptr addrspace(200) nonnull [[S_0]], ptr addrspace(200) [[STR]])
; CHECK-PURECAP-RV32-NEXT:    ret i32 [[TMP1]]
;
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.cond, %entry
  %s.0 = phi ptr addrspace(200) [ %str, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr addrspace(200) %s.0, align 1
  %tobool.not = icmp eq i8 %0, 0
  %incdec.ptr = getelementptr inbounds nuw i8, ptr addrspace(200) %s.0, i32 1
  br i1 %tobool.not, label %for.end, label %for.cond

for.end:                                          ; preds = %for.cond
  %1 = tail call i32 @llvm.cheri.cap.diff.i32(ptr addrspace(200) nonnull %s.0, ptr addrspace(200) %str)
  ret i32 %1
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.cheri.cap.diff.i32(ptr addrspace(200), ptr addrspace(200)) addrspace(200) #1

attributes #0 = { minsize nofree nosync nounwind optsize memory(argmem: read)}
attributes #1 = { mustprogress nofree nosync nounwind willreturn memory(none) }
