; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: %riscv32_cheri_purecap_opt < %s -loop-reduce -S | \
; RUN:   FileCheck %s --check-prefix=RV32-PURECAP-CHECK
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"

@buf = dso_local local_unnamed_addr addrspace(200) global [10 x [10 x i8]] zeroinitializer, align 1

; Verify that LSR does not hoist the address offset out of the inner loop.

; Function Attrs: minsize nofree norecurse nosync nounwind optsize memory(write, argmem: none, inaccessiblemem: none)
define dso_local void @f(i32 noundef %y_offset) local_unnamed_addr addrspace(200) #0 {
; RV32-PURECAP-CHECK-LABEL: define dso_local void @f(
; RV32-PURECAP-CHECK-SAME: i32 noundef [[Y_OFFSET:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; RV32-PURECAP-CHECK-NEXT:  [[ENTRY:.*]]:
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_COND:.*]]
; RV32-PURECAP-CHECK:       [[FOR_COND]]:
; RV32-PURECAP-CHECK-NEXT:    [[X_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC13:%.*]], %[[CLEANUP:.*]] ]
; RV32-PURECAP-CHECK-NEXT:    [[EXITCOND24_NOT:%.*]] = icmp eq i32 [[X_0]], 10
; RV32-PURECAP-CHECK-NEXT:    br i1 [[EXITCOND24_NOT]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_COND1_PREHEADER:.*]]
; RV32-PURECAP-CHECK:       [[FOR_COND1_PREHEADER]]:
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_COND1:.*]]
; RV32-PURECAP-CHECK:       [[FOR_COND_CLEANUP]]:
; RV32-PURECAP-CHECK-NEXT:    ret void
; RV32-PURECAP-CHECK:       [[FOR_COND1]]:
; RV32-PURECAP-CHECK-NEXT:    [[Y_0:%.*]] = phi i32 [ [[INC:%.*]], %[[FOR_INC:.*]] ], [ 0, %[[FOR_COND1_PREHEADER]] ]
; RV32-PURECAP-CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[Y_0]], 10
; RV32-PURECAP-CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[CLEANUP]], label %[[FOR_BODY4:.*]]
; RV32-PURECAP-CHECK:       [[FOR_BODY4]]:
; RV32-PURECAP-CHECK-NEXT:    [[LSR_IV1:%.*]] = add nsw i32 [[Y_0]], [[Y_OFFSET]]
; RV32-PURECAP-CHECK-NEXT:    [[CMP5:%.*]] = icmp slt i32 [[LSR_IV1]], 0
; RV32-PURECAP-CHECK-NEXT:    br i1 [[CMP5]], label %[[FOR_INC]], label %[[IF_END:.*]]
; RV32-PURECAP-CHECK:       [[IF_END]]:
; RV32-PURECAP-CHECK-NEXT:    [[CMP7:%.*]] = icmp ugt i32 [[LSR_IV1]], 9
; RV32-PURECAP-CHECK-NEXT:    br i1 [[CMP7]], label %[[CLEANUP]], label %[[IF_END9:.*]]
; RV32-PURECAP-CHECK:       [[IF_END9]]:
; RV32-PURECAP-CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr inbounds nuw [10 x [10 x i8]], ptr addrspace(200) @buf, i32 0, i32 [[X_0]], i32 [[LSR_IV1]]
; RV32-PURECAP-CHECK-NEXT:    store i8 1, ptr addrspace(200) [[SCEVGEP2]], align 1
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_INC]]
; RV32-PURECAP-CHECK:       [[FOR_INC]]:
; RV32-PURECAP-CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[Y_0]], 1
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_COND1]]
; RV32-PURECAP-CHECK:       [[CLEANUP]]:
; RV32-PURECAP-CHECK-NEXT:    [[INC13]] = add nuw nsw i32 [[X_0]], 1
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_COND]]
;
entry:
  br label %for.cond

for.cond:                                         ; preds = %cleanup, %entry
  %x.0 = phi i32 [ 0, %entry ], [ %inc13, %cleanup ]
  %exitcond24.not = icmp eq i32 %x.0, 10
  br i1 %exitcond24.not, label %for.cond.cleanup, label %for.cond1

for.cond.cleanup:                                 ; preds = %for.cond
  ret void

for.cond1:                                        ; preds = %for.cond, %for.inc
  %y.0 = phi i32 [ %inc, %for.inc ], [ 0, %for.cond ]
  %exitcond.not = icmp eq i32 %y.0, 10
  br i1 %exitcond.not, label %cleanup, label %for.body4

for.body4:                                        ; preds = %for.cond1
  %add = add nsw i32 %y.0, %y_offset
  %cmp5 = icmp slt i32 %add, 0
  br i1 %cmp5, label %for.inc, label %if.end

if.end:                                           ; preds = %for.body4
  %cmp7 = icmp ugt i32 %add, 9
  br i1 %cmp7, label %cleanup, label %if.end9

if.end9:                                          ; preds = %if.end
  %arrayidx11 = getelementptr inbounds nuw [10 x [10 x i8]], ptr addrspace(200) @buf, i32 0, i32 %x.0, i32 %add
  store i8 1, ptr addrspace(200) %arrayidx11, align 1
  br label %for.inc

for.inc:                                          ; preds = %for.body4, %if.end9
  %inc = add nuw nsw i32 %y.0, 1
  br label %for.cond1

cleanup:                                          ; preds = %if.end, %for.cond1
  %inc13 = add nuw nsw i32 %x.0, 1
  br label %for.cond
}

attributes #0 = { minsize nofree norecurse nosync nounwind optsize memory(write, argmem: none, inaccessiblemem: none)}
