; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: %riscv32_cheri_purecap_opt < %s -loop-reduce -S | \
; RUN:   FileCheck %s --check-prefix=RV32-PURECAP-CHECK
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"

@buf = dso_local local_unnamed_addr addrspace(200) global [10 x i8] zeroinitializer, align 1

; Verify that LSR does not hoist the address offset out of the inner loop.

; Function Attrs: minsize nofree norecurse nosync nounwind optsize memory(write, argmem: none, inaccessiblemem: none)
define dso_local void @f(i32 noundef %y_offset) local_unnamed_addr addrspace(200) #0 {
; RV32-PURECAP-CHECK-LABEL: define dso_local void @f(
; RV32-PURECAP-CHECK-SAME: i32 noundef [[Y_OFFSET:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; RV32-PURECAP-CHECK-NEXT:  [[ENTRY:.*]]:
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_COND:.*]]
; RV32-PURECAP-CHECK:       [[FOR_COND]]:
; RV32-PURECAP-CHECK-NEXT:    [[LSR_IV1:%.*]] = phi i32 [ [[LSR_IV_NEXT2:%.*]], %[[FOR_INC:.*]] ], [ 10, %[[ENTRY]] ]
; RV32-PURECAP-CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[LSR_IV_NEXT:%.*]], %[[FOR_INC]] ], [ [[Y_OFFSET]], %[[ENTRY]] ]
; RV32-PURECAP-CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[LSR_IV1]], 0
; RV32-PURECAP-CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[CLEANUP:.*]], label %[[FOR_BODY:.*]]
; RV32-PURECAP-CHECK:       [[FOR_BODY]]:
; RV32-PURECAP-CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[LSR_IV]], 0
; RV32-PURECAP-CHECK-NEXT:    br i1 [[CMP1]], label %[[FOR_INC]], label %[[IF_END:.*]]
; RV32-PURECAP-CHECK:       [[IF_END]]:
; RV32-PURECAP-CHECK-NEXT:    [[CMP3:%.*]] = icmp samesign ugt i32 [[LSR_IV]], 9
; RV32-PURECAP-CHECK-NEXT:    br i1 [[CMP3]], label %[[CLEANUP]], label %[[IF_END5:.*]]
; RV32-PURECAP-CHECK:       [[IF_END5]]:
; RV32-PURECAP-CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr addrspace(200) @buf, i32 [[LSR_IV]]
; RV32-PURECAP-CHECK-NEXT:    store i8 1, ptr addrspace(200) [[SCEVGEP]], align 1
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_INC]]
; RV32-PURECAP-CHECK:       [[FOR_INC]]:
; RV32-PURECAP-CHECK-NEXT:    [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], 1
; RV32-PURECAP-CHECK-NEXT:    [[LSR_IV_NEXT2]] = add nsw i32 [[LSR_IV1]], -1
; RV32-PURECAP-CHECK-NEXT:    br label %[[FOR_COND]]
; RV32-PURECAP-CHECK:       [[CLEANUP]]:
; RV32-PURECAP-CHECK-NEXT:    ret void
;
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %y.0 = phi i32 [ 0, %entry ], [ %inc, %for.inc ]
  %exitcond.not = icmp eq i32 %y.0, 10
  br i1 %exitcond.not, label %cleanup, label %for.body

for.body:                                         ; preds = %for.cond
  %add = add nsw i32 %y.0, %y_offset
  %cmp1 = icmp slt i32 %add, 0
  br i1 %cmp1, label %for.inc, label %if.end

if.end:                                           ; preds = %for.body
  %cmp3 = icmp samesign ugt i32 %add, 9
  br i1 %cmp3, label %cleanup, label %if.end5

if.end5:                                          ; preds = %if.end
  %arrayidx = getelementptr inbounds nuw [10 x i8], ptr addrspace(200) @buf, i32 0, i32 %add
  store i8 1, ptr addrspace(200) %arrayidx, align 1
  br label %for.inc

for.inc:                                          ; preds = %for.body, %if.end5
  %inc = add nuw nsw i32 %y.0, 1
  br label %for.cond

cleanup:                                          ; preds = %if.end, %for.cond
  ret void
}

attributes #0 = { minsize nofree norecurse nosync nounwind optsize memory(write, argmem: none, inaccessiblemem: none)}
