; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+xcheri,+cap-mode,+cheri-bounded-vararg,+cheri-bounded-memarg-caller,+cheri-bounded-memarg-callee -target-abi l64pc128d -o - %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+xcheri,+cap-mode -target-abi l64pc128d -o - %s | FileCheck %s

; Check that memory arguments are read from the stack and not through bounded arg pointer - it will be clobbered with fastcc
define fastcc i32 @y(i32 %a0, i32 %a1, i32 %a2, i32 %a3, i32 %a4, i32 %a5, i32 %a6, i32 %a7, i32 %t2, i32 %t3, i32 %t4, i32 %t5, i32 %t6, i32 %m0) {
; CHECK-LABEL: y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset csp, csp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    mv a3, t6
; CHECK-NEXT:    mv a2, t5
; CHECK-NEXT:    mv a1, t4
; CHECK-NEXT:    ld a4, 16(csp)
; CHECK-NEXT:    ld a5, 24(csp)
; CHECK-NEXT:    mv a0, t3
; CHECK-NEXT:    call x
; CHECK-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    cincoffset csp, csp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %call = call i32 @x(i32 %t2, i32 %t3, i32 %t4, i32 %t5, i32 %t6, i32 %m0)
  ret i32 %call
}

declare i32 @x(i32, i32, i32, i32, i32, i32)
