; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: %riscv64_cheri_purecap_llc -mattr=+a < %s | FileCheck %s
; RUN: %riscv64_cheri_purecap_llc -mattr=+a -no-integrated-as < %s | FileCheck %s --check-prefix=RAW

; Check that a "C"-constrained operand is spelled the way the mnemonic
; expects: "c"-prefixed for xcheri/ISAv9, plain GPR names for RVY (y-family).
; RAW shows the text we emit; CHECK shows it after the integrated assembler
; round-trips it, which only succeeds if the spelling was accepted.

define ptr addrspace(200) @test_load(ptr addrspace(200) %cap) nounwind {
; CHECK-LABEL: test_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lc ca0, 16(ca0)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_load:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    clc ca0, 16(ca0)
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "clc $0, $1($2)", "=C,i,C"(i32 16, ptr addrspace(200) %cap)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @test_load_rvy_alias(ptr addrspace(200) %cap) nounwind {
; CHECK-LABEL: test_load_rvy_alias:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lc ca0, 16(ca0)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_load_rvy_alias:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    ly a0, 16(a0)
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "ly $0, $1($2)", "=C,i,C"(i32 16, ptr addrspace(200) %cap)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @test_add(ptr addrspace(200) %cap, i64 %add) nounwind {
; CHECK-LABEL: test_add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    cincoffset ca0, ca0, a1
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_add:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    cincoffset ca0, ca0, a1
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "cincoffset $0, $1, $2", "=C,C,r"(ptr addrspace(200) %cap, i64 %add)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @test_add_rvy_alias(ptr addrspace(200) %cap, i64 %add) nounwind {
; CHECK-LABEL: test_add_rvy_alias:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    cincoffset ca0, ca0, a1
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_add_rvy_alias:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    yadd a0, a0, a1
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "yadd $0, $1, $2", "=C,C,r"(ptr addrspace(200) %cap, i64 %add)
  ret ptr addrspace(200) %0
}

; A memory constraint picks the base register via PrintAsmMemoryOperand.
define ptr addrspace(200) @test_load_mem(ptr addrspace(200) %cap) nounwind {
; CHECK-LABEL: test_load_mem:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lc ca0, 0(ca0)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_load_mem:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    clc ca0, 0(ca0)
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "clc $0, $1", "=C,*m"(ptr addrspace(200) elementtype(i64) %cap)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @test_load_mem_rvy_alias(ptr addrspace(200) %cap) nounwind {
; CHECK-LABEL: test_load_mem_rvy_alias:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lc ca0, 0(ca0)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_load_mem_rvy_alias:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    ly a0, 0(a0)
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "ly $0, $1", "=C,*m"(ptr addrspace(200) elementtype(i64) %cap)
  ret ptr addrspace(200) %0
}

; The "y" that picks the RVY spelling can appear anywhere in the mnemonic,
; not just as a prefix, e.g. the ".y" suffix on an atomic mnemonic.
define ptr addrspace(200) @test_amoswap(ptr addrspace(200) %addr, ptr addrspace(200) %val) nounwind {
; CHECK-LABEL: test_amoswap:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    amoswap.c ca0, ca1, (ca0)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_amoswap:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    amoswap.c ca0, ca1, (ca0)
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "amoswap.c $0, $2, ($1)", "=C,C,C"(ptr addrspace(200) %addr, ptr addrspace(200) %val)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @test_amoswap_rvy_alias(ptr addrspace(200) %addr, ptr addrspace(200) %val) nounwind {
; CHECK-LABEL: test_amoswap_rvy_alias:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    amoswap.c ca0, ca1, (ca0)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
;
; RAW-LABEL: test_amoswap_rvy_alias:
; RAW:       # %bb.0: # %entry
; RAW-NEXT:    #APP
; RAW-NEXT:    amoswap.y a0, a1, (a0)
; RAW-NEXT:    #NO_APP
; RAW-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) asm "amoswap.y $0, $2, ($1)", "=C,C,C"(ptr addrspace(200) %addr, ptr addrspace(200) %val)
  ret ptr addrspace(200) %0
}
