; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: %riscv64_cheri_purecap_llc < %s | FileCheck --check-prefix=PURECAP %s
; RUN: %riscv64_cheri_llc < %s | FileCheck --check-prefix=HYBRID %s

; Check that getRegisterByName() uses the requested type to pick between a
; GPR and the capability register aliasing it (they share both their
; architectural and ABI names, e.g. "x4"/"tp").

define ptr addrspace(200) @get_cap_arch_name() nounwind {
; PURECAP-LABEL: get_cap_arch_name:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cmove ca0, ctp
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: get_cap_arch_name:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cmove ca0, ctp
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.read_register.p200i8(metadata !0)
  ret ptr addrspace(200) %0
}

define i64 @get_int_arch_name() nounwind {
; PURECAP-LABEL: get_int_arch_name:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    mv a0, tp
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: get_int_arch_name:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    mv a0, tp
; HYBRID-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.read_register.i64(metadata !0)
  ret i64 %0
}

define ptr addrspace(200) @get_cap_abi_name() nounwind {
; PURECAP-LABEL: get_cap_abi_name:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cmove ca0, ctp
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: get_cap_abi_name:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cmove ca0, ctp
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.read_register.p200i8(metadata !1)
  ret ptr addrspace(200) %0
}

define i64 @get_int_abi_name() nounwind {
; PURECAP-LABEL: get_int_abi_name:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    mv a0, tp
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: get_int_abi_name:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    mv a0, tp
; HYBRID-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.read_register.i64(metadata !1)
  ret i64 %0
}

define void @set_cap_arch_name(ptr addrspace(200) %value) nounwind {
; PURECAP-LABEL: set_cap_arch_name:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset csp, csp, -16
; PURECAP-NEXT:    sc cgp, 0(csp) # 16-byte Folded Spill
; PURECAP-NEXT:    cmove cgp, ca0
; PURECAP-NEXT:    lc cgp, 0(csp) # 16-byte Folded Reload
; PURECAP-NEXT:    cincoffset csp, csp, 16
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: set_cap_arch_name:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cmove cgp, ca0
; HYBRID-NEXT:    ret
entry:
  tail call void @llvm.write_register.p200i8(metadata !2, ptr addrspace(200) %value)
  ret void
}

define void @set_int_arch_name(i64 %value) nounwind {
; PURECAP-LABEL: set_int_arch_name:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset csp, csp, -16
; PURECAP-NEXT:    sc cgp, 0(csp) # 16-byte Folded Spill
; PURECAP-NEXT:    mv gp, a0
; PURECAP-NEXT:    lc cgp, 0(csp) # 16-byte Folded Reload
; PURECAP-NEXT:    cincoffset csp, csp, 16
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: set_int_arch_name:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    mv gp, a0
; HYBRID-NEXT:    ret
entry:
  tail call void @llvm.write_register.i64(metadata !2, i64 %value)
  ret void
}

declare ptr addrspace(200) @llvm.read_register.p200i8(metadata)
declare i64 @llvm.read_register.i64(metadata)
declare void @llvm.write_register.p200i8(metadata, ptr addrspace(200))
declare void @llvm.write_register.i64(metadata, i64)

!llvm.named.register.x4 = !{!0}
!llvm.named.register.tp = !{!1}
!llvm.named.register.x3 = !{!2}

!0 = !{!"x4"}
!1 = !{!"tp"}
!2 = !{!"x3"}
