// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %cheri_purecap_cc1 -emit-llvm %s -o - -verify | FileCheck %s -check-prefix PURECAP
// expected-no-diagnostics
// RUN: %cheri_purecap_cc1 -emit-llvm -fsanitize=alignment %s -o - -verify | FileCheck %s -check-prefix PURECAP-ALIGN
// expected-no-diagnostics

// PURECAP-LABEL: define dso_local ptr addrspace(200) @foo
// PURECAP-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[OVER_BOUNDARY:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP0]], i64 15
// PURECAP-NEXT:    [[ALIGNED_RESULT:%.*]] = call ptr addrspace(200) @llvm.ptrmask.p200.i64(ptr addrspace(200) [[OVER_BOUNDARY]], i64 -16)
// PURECAP-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
// PURECAP-ALIGN-LABEL: define dso_local ptr addrspace(200) @foo
// PURECAP-ALIGN-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-ALIGN-NEXT:  entry:
// PURECAP-ALIGN-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-ALIGN-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[OVER_BOUNDARY:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP0]], i64 15
// PURECAP-ALIGN-NEXT:    [[ALIGNED_RESULT:%.*]] = call ptr addrspace(200) @llvm.ptrmask.p200.i64(ptr addrspace(200) [[OVER_BOUNDARY]], i64 -16)
// PURECAP-ALIGN-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
void *foo(__UINTPTR_TYPE__ cap) {
  return (void *)__builtin_align_up(cap, 16);
}

// PURECAP-LABEL: define dso_local ptr addrspace(200) @bar
// PURECAP-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[ALIGNED_RESULT:%.*]] = call ptr addrspace(200) @llvm.ptrmask.p200.i64(ptr addrspace(200) [[TMP0]], i64 -16)
// PURECAP-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
// PURECAP-ALIGN-LABEL: define dso_local ptr addrspace(200) @bar
// PURECAP-ALIGN-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-ALIGN-NEXT:  entry:
// PURECAP-ALIGN-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-ALIGN-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[ALIGNED_RESULT:%.*]] = call ptr addrspace(200) @llvm.ptrmask.p200.i64(ptr addrspace(200) [[TMP0]], i64 -16)
// PURECAP-ALIGN-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
void *bar(__UINTPTR_TYPE__ cap) {
  return (void *)__builtin_align_down(cap, 16);
}

