; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; UNSUPPORTED: true
; RUN: opt -S -mtriple=riscv64 -pre-isel-intrinsic-lowering -mem-intrinsic-expand-size=0 --print-before-all < %s | FileCheck %s --check-prefixes=CHECK,RISCV
; RUN: opt -S -mtriple=riscv64 -data-layout="pf200:128:128:128:64" -mem-intrinsic-expand-size=0 -pre-isel-intrinsic-lowering < %s | FileCheck %s --check-prefixes=CHECK,HYBRID

define i1 @icmp_ueq(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ueq ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_ugt(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ugt ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_uge(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp uge ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_ult(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ult ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_ule(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ule ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_une(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp une ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_eq(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp eq ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_gt(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp gt ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_ge(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ge ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_lt(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ugt ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_le(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ugt ptr addrspace(200) %ptr, %ptr
}

define i1 @icmp_ne(ptr addrspace(200) %ptr) #0 {
entry:
  ret i1 icmp ne ptr addrspace(200) %ptr, %ptr
}
